### PR TITLE
Add two new function: network and auto blending 

### PR DESCRIPTION
**Pull request by chenchengshao**

### CODE REVIEW

**Comment by jrgnicho** [comment]
Do the changes here make the current PR #1 Obsolete?

**Comment by chenchengshao** [comment]
Yes,This change will include all the network and auto_blending function. PR
#1 https://github.com/ros-industrial-consortium/godel/issues/1 will
Obsolete.

**Comment by jrgnicho** [comment]
The PR is supposed to be submitted to the [swri-robotics fork](https://github.com/swri-robotics/godel).

**Comment by chenchengshao** [comment]
Just submitted to swri-robotics fork
https://github.com/swri-robotics/godel, also close old two PRs.

https://github.com/swri-robotics/godel/pull/2

**Pull request closed without merging**
