### PR TITLE
standalone visualization complete

### PR DESCRIPTION
**Pull request by dpsolomon**

### CODE REVIEW

**Comment by jrgnicho** [comment]
There was a build error caused by the godel_process_path_generation package

[path to godel metapackage]/godel_process_path_generation/include/godel_process_path_generation/process_path_generator.h:29:42: fatal error: openvoronoi/voronoidiagram.hpp: No such file or directory
compilation terminated.
make[2]: **\* [godel/godel_process_path_generation/CMakeFiles/process_path_generator.dir/src/process_path_generator.cpp.o] Error 1
make[1]: **\* [godel/godel_process_path_generation/CMakeFiles/process_path_generator.dir/all] Error 2
make: **\* [all] Error 2

The openvoronoi library https://github.com/aewallin/openvoronoi is missing.

**Comment by dpsolomon** [comment]
openvoronoi should be installed. I cannot get cmake to register the package at this time, so it doesn't halt the build nicely. Instructions are at https://github.com/ros-industrial-consortium/godel/blob/hydro-devel/godel_process_path_generation/README.md, I recommend building from source

**Comment by gavanderhoorn** [comment]
@dpsolomon wrote:

> I recommend building from source

~~openvoronoi seems to use CMake itself. Wouldn't it be possible to release it as a 3rd party catkin package? See [bloom/Tutorials/ReleaseThirdParty](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty).~~

nvm, I hadn't seen openvoronoi has a PPA.

**Comment by jrgnicho** [comment]
After following the instructions in the README file I ran into the following
- the openvoronoi library built and installed successfully from source.
- the patch step produced the following error message:

ros-hydro: cd godel_process_path_generation/
ros-hydro: sudo patch /usr/local/include/openvoronoi/offset_sorter.hpp < src/offset_sorter.patch
patching file /usr/local/include/openvoronoi/offset_sorter.hpp
Hunk #2 FAILED at 297.
1 out of 2 hunks FAILED -- saving rejects to file /usr/local/include/openvoronoi/offset_sorter.hpp.rej
- A second attempt at applying the patch produced the following error:

ros-hydro: sudo patch /usr/local/include/openvoronoi/offset_sorter.hpp < src/offset_sorter.patch
patching file /usr/local/include/openvoronoi/offset_sorter.hpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] y
Hunk #1 FAILED at 142.
Hunk #2 FAILED at 292.
2 out of 2 hunks FAILED -- saving rejects to file /usr/local/include/openvoronoi/offset_sorter.hpp.rej
- I tried building the catkin workspace regardless and I got the following build error:

In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /usr/local/include/openvoronoi/offset_sorter.hpp:28,
                 from [Home]ros/hydro/catkin_ws/src/godel/godel_process_path_generation/include/godel_process_path_generation/process_path_generator.h:30,
                 from [Home]/ros/hydro/catkin_ws/src/godel/godel_process_path_generation/src/process_path_generator.cpp:26:
/usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
compilation terminated.
make[2]: **\* [godel/godel_process_path_generation/CMakeFiles/process_path_generator.dir/src/process_path_generator.cpp.o] Error 1
make[1]: **\* [godel/godel_process_path_generation/CMakeFiles/process_path_generator.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

Are there any other system dependencies missing?

**Comment by shaun-edwards** [comment]
@dpsolomon, can we add the installation instructions to the main readme (the one that gets displayed at the repo level).  This would make the instructions more apparent to the user.  This is also in line with how packages are released (i.e. as a repo).

**Comment by gavanderhoorn** [comment]
@jrgnicho: I had the same problems yesterday trying to get it to build. There is something strange going on with openvoronoi and its Python bindings.

Also: last build of the openvoronoi deb in the PPA seems to have taken place some 80 weeks ago, and the version that is currently released doesn't install for me on ubuntu 12.04 (unsatisfiable dependency on `libboost-python`).

**Pull request merged**
