### PR TITLE
Milestone 3 Development Code

### PR DESCRIPTION
**Pull request by Jmeyer1292**
First off, my apologies for what is an enormous pull request. This includes the milestone 2 development software as well as progress on milestone 3.

The major highlights are:
    Kinect 2 integration
    Calibration routines
    Laser scan analysis code
    Primitive Cartesian motion using Descartes
    Multiple robots
    Save/Load motion plans
    Persistent configurations
    New menus for setting process parameters
    New robot motion preview    

On the near horizon:
    Improvements the laser scanner driver / system
    Improvements to the HMI for macro scanning

I used https://github.com/code-iai/iai_kinect2 to communicate with the Kinect 2. 

Thank you

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Is there any possibility of splitting this into multiple smaller PRs? Even if it's impossible to group commits according to features (or something), just cutting this up in chunks of N commits would already help I think.

**Comment by shaun-edwards** [comment]
I agree with @gavanderhoorn

**Comment by Jmeyer1292** [comment]
I'll figure out something

**Comment by gavanderhoorn** [comment]
This was closed in favour of the more piece-wise PRs?

**Pull request closed without merging**
