### PR TITLE
Updated message/service definitions

### PR DESCRIPTION
**Pull request by dpsolomon**

### CODE REVIEW

**Comment by dpsolomon** [comment]
A clean build may be necessary at this point because of how some of the messages were moved around. 'catkin_make clean' did not work for me, so I manually deleted the workspace build/ and devel/ directories, and even most of the catkin/cmake directories in the individual packages before it would rebuild properly. Afterward all builds work properly, repeatedly.

**Comment by jrgnicho** [comment]
+1

**Comment by gavanderhoorn** [comment]
@dpsolomon wrote:

> [..] so I manually deleted the workspace build/ and devel/ directories, and even most of the catkin/cmake directories in the individual packages before it would rebuild properly.

'cmake directories in individual packages'? Shouldn't catkin/cmake do an out-of-source build, and only generate build artefacts in the `devel` and `build` dirs?

**Comment by dpsolomon** [comment]
You are correct. I believe those were left over from building individual eclipse project files using cmake.

**Comment by gavanderhoorn** [comment]
Ok, thanks. Just wondering.

**Pull request merged**
